apiVersion: v1
kind: Pod
metadata:
  name: cuda-validate
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-validate
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
